name: Publish Container

on:
  workflow_dispatch:
    inputs:
      old_line:
        description: The line that needs to be changed (e.g. tag1)
        type: string
        required: true
      new_line:
        description: The replacement line (e.g. tag2)
        type: string
        required: true

permissions:
  contents: write

jobs:
  change_line:
    name: Change line
    uses: ./.github/workflows/change_line.yaml
    with:
      old_line: ${{ inputs.old_line }}
      new_line: ${{ inputs.new_line }}
      file_path: message.txt
  publish:
    needs: change_line
    name: Publish Container
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: echo publish
